show databases;
CREATE DATABASE PROJECT_SQL;
USE PROJECT_SQL;
SHOW TABLES;
CREATE TABLE EMP_RECORD
(EMP_ID VARCHAR(10), FIRST_NAME VARCHAR(40), LAST_NAME VARCHAR(40), GENDER VARCHAR(6), ROLE VARCHAR(50), DEPT VARCHAR(50), EXP INT,
COUNTRY VARCHAR(20), CONTINENT VARCHAR(30), SALARY INT, EMP_RATING INT , MANAGER_ID VARCHAR(20), PROJ_ID VARCHAR(10) );
INSERT INTO EMP_RECORD VALUES
('E001','Arthur','Black','M','PRESIDENT','ALL',20,'USA','NORTH AMERICA',16500,5,NULL,NULL),
('E005','Eric','Hoffman','M','LEAD DATA SCIENTIST','FINANCE',11,'USA',"NORTH AMERICA",8500,3,'E103','P105'),
('E010','William','Butler','M',"LEAD DATA SCIENTIST",'AUTOMOTIVE',12,'FRANCE','EUROPE',9000,2,'E428','P204'),
('E052','Dianna','Wilson','F',"SENIOR DATA SCIENTIST",'HEALTHCARE','6','CANADA',"NORTH AMERICA",5500,5,'E083','P103'),
('E057','Dorothy','Wilson','F',"SENIOR DATA SCIENTIST",'HEALTHCARE',9,'USA',"NORTH AMERICA",7700,1,'E083','P302'),
('E083','Patrick','Voltz','M','MANAGER','HEALTHCARE',15,'USA',"NORTH AMERICA",9500,5,'E001',NULL),
('E103','Emily','Grove','F','MANAGER','FINANCE',14,'CANADA',"NORTH AMERICA",10500,4,'E001',NULL),
('E204','Karene','Nowak','F',"SENIOR DATA SCIENTIST",'AUTOMOTIVE',8,'GERMANY','EUROPE',7500,5,'E428','P204'),
('E245','Nian','Zhen','M',"SENIOR DATA SCIENTIST",'RETAIL',6,'CHINA','ASIA',6500,2,'E583','P109'),
('E260','Roy','Collins','M',"SENIOR DATA SCIENTIST",'RETAIL',7,'INDIA','ASIA',7000,3,'E583','NA'),
('E403','Steve','Hoffman','M',"ASSOCIATE DATA SCIENTIST",'FINANCE',4,'USA',"NORTH AMERICA",5000,3,'E103','P105'),
('E428','Pete','Allen','M','MANAGER','AUTOMOTIVE',14,'GERMANY','EUROPE',11000,4,'E001',NULL),
('E478','David','Smith','M',"ASSOCIATE DATA SCIENTIST",'RETAIL',3,'COLOMBIA',"SOUTH AMERICA",4000,4,'E583','P109'),
('E505','Chad','Wilson','M',"ASSOCIATE DATA SCIENTIST",'HEALTHCARE',5,'CANADA',"NORTH AMERICA",5000,2,'E083','P103'),
('E532','Claire','Brennan','F',"ASSOCIATE DATA SCIENTIST",'AUTOMOTIVE',3,'GERMANY','EUROPE',4300,1,'E428','P204'),
('E583','Janet','Hale','F','MANAGER','RETAIL',14,'COLOMBIA',"SOUTH AMERICA",10000,2,'E001',NULL),
('E612','Tracy','Norris','F','MANAGER','RETAIL',13,'INDIA','ASIA',8500,4,'E001',NULL),
('E620','Katrina','Allen','F',"JUNIOR DATA SCIENTIST",'RETAIL',2,'INDIA','ASIA',3000,1,'E612','P406'),
('E640','Jenifer','Jhones','F',"JUNIOR DATA SCIENTIST",'RETAIL',1,'COLOMBIA',"SOUTH AMERICA",2800,4,'E612','P406');

CREATE TABLE PROJECT
(PROJECT_ID VARCHAR(10), PROJ_NAME VARCHAR(40), DOMAIN VARCHAR(40), START_DATE DATE, CLOSURE_DATE DATE,
 DEV_QTR VARCHAR(10), STATUS VARCHAR(20));
 
 INSERT INTO PROJECT VALUES
 ('P103','Drug Discovery','HEALTHCARE','2021-06-04','2021-06-20','Q1','DONE'),
('P105','Fraud Detection','FINANCE','2021-11-04','2021-06-25','Q1','DONE'),
('P109','Market Basket Analysis','RETAIL','2021-12-04','2021-06-30','Q1','DELAYED'),
('P204','Supply Chain Management','AUTOMOTIVE','2021-07-15','2021-09-28','Q2','WIP'),
('P302','Early Detection of Lung Cancer','HEALTHCARE','2021-08-10','2021-12-18','Q3','YTS'),
('P406','Customer Sentiment Analysis', 'RETAIL','2021-09-07','2021-09-24','Q2','WIP');

CREATE TABLE DATA_SCIENCE_TEAM
(EMP_ID VARCHAR(10), FIRST_NAME VARCHAR(40), LAST_NAME VARCHAR(40), GENDER VARCHAR(10), ROLE VARCHAR(50),
 DEPT VARCHAR(50), EXP INT, COUNTRY  VARCHAR(40), CONTINENT VARCHAR(40));
 
INSERT INTO DATA_SCIENCE_TEAM VALUES
('E005','Eric','Hoffman','M',"LEAD DATA SCIENTIST",'FINANCE',11,'USA',"NORTH AMERICA"),
('E010','William','Butler','M',"LEAD DATA SCIENTIST",'AUTOMOTIVE',12,'FRANCE','EUROPE'),
('E052','Dianna','Wilson','F',"SENIOR DATA SCIENTIST",'HEALTHCARE',6,'CANADA',"NORTH AMERICA"),
('E057','Dorothy','Wilson','F',"SENIOR DATA SCIENTIST",'HEALTHCARE',9,'USA',"NORTH AMERICA"),
('E204','Karene','Nowak','F',"SENIOR DATA SCIENTIST",'AUTOMOTIVE',8,'GERMANY','EUROPE'),
('E245','Nian','Zhen','M',"SENIOR DATA SCIENTIST",'RETAIL',6,'CHINA','ASIA'),
('E260','Roy','Collins','M',"SENIOR DATA SCIENTIST",'RETAIL',7,'INDIA','ASIA'),
('E403','Steve','Hoffman','M',"ASSOCIATE DATA SCIENTIST",'FINANCE',4,'USA',"NORTH AMERICA"),
('E478','David','Smith','M',"ASSOCIATE DATA SCIENTIST",'RETAIL',3,'COLOMBIA',"SOUTH AMERICA"),
('E505','Chad','Wilson','M',"ASSOCIATE DATA SCIENTIST",'HEALTHCARE',5,'CANADA',"NORTH AMERICA"),
('E532','Claire','Brennan','F',"ASSOCIATE DATA SCIENTIST",'AUTOMOTIVE',3,'GERMANY','EUROPE'),
('E620','Katrina','Allen','F',"JUNIOR DATA SCIENTIST",'RETAIL',2,'INDIA','ASIA'),
('E640','Jenifer','Jhones','F',"JUNIOR DATA SCIENTIST",'RETAIL',1,'COLOMBIA',"SOUTH AMERICA");

SELECT EMP_ID, FIRST_NAME, LAST_NAME, GENDER, DEPT FROM EMP_RECORD;
SELECT EMP_ID,FIRST_NAME,LAST_NAME,GENDER,DEPT,EMP_RATING FROM EMP_RECORD WHERE EMP_RATING > 2 AND EMP_RATING < 4;
SELECT FIRST_NAME, LAST_NAME , CONCAT(FIRST_NAME,'  ' , LAST_NAME) AS NAME FROM EMP_RECORD WHERE DEPT="FINANCE";

SELECT * FROM project_sql.emp_record where EXP > 3;
SELECT MANAGER_ID, FIRST_NAME, LAST_NAME, COUNT(EMP_ID) as EMP_COUNT FROM EMP_RECORD GROUP BY MANAGER_ID ORDER BY EMP_COUNT DESC;
SELECT * FROM EMP_RECORD WHERE DEPT = 'FINANCE'
UNION 
SELECT * FROM EMP_RECORD WHERE DEPT = 'HEALTHCARE';

#SELECT EMP_ID, FIRST_NAME, LAST_NAME, DEPT, EMP_RATING FROM EMP_RECORD GROUP BY DEPT IN 
#(SELECT MAX(EMP_RATING) AS MAXIMUM_RATING  FROM emp_record);

SELECT MAX(SALARY) AS MAX_SALARY, MIN(SALARY) AS MIN_SALARY, DEPT FROM EMP_RECORD GROUP BY DEPT;

SELECT CONCAT(FIRST_NAME,' ',LAST_NAME) AS NAME, EXP , RANK() OVER (ORDER BY EXP DESC) AS RANKING FROM EMP_RECORD ;

SELECT CONCAT(FIRST_NAME,' ',LAST_NAME) AS NAME,SALARY, COUNTRY FROM EMP_RECORD 
WHERE SALARY > 6000 ORDER BY SALARY DESC;

SELECT CONCAT(FIRST_NAME,' ',LAST_NAME) AS NAME, 
EXP  FROM EMP_RECORD WHERE EXP > 10;

select * from EMP_RECORD;

DELIMITER $$ 
CREATE PROCEDURE GetExpEmp2()
BEGIN
    SELECT * FROM EMP_RECORD
    WHERE EXP  >= 3 ;
END$$
CALL GetExpEmp2() ;

DELIMITER &&
CREATE FUNCTION Employee_ROLE(EXP int)RETURNS VARCHAR(40)
DETERMINISTIC 
BEGIN
DECLARE Employee_ROLE VARCHAR(40);
IF EXP>12 AND 16 THEN SET Employee_ROLE="MANAGER";
ELSEIF EXP>10 AND 12 THEN SET Employee_ROLE ="LEAD DATA SCIENTIST";
ELSEIF EXP>5 AND 10 THEN SET Employee_ROLE ="SENIOR DATA SCIENTIST";
ELSEIF EXP>2 AND 5 THEN SET Employee_ROLE ="ASSOCIATE DATA SCIENTIST";
ELSEIF EXP<=2 THEN SET Employee_ROLE ="JUNIOR DATA SCIENTIST";
END IF;
RETURN (Employee_ROLE);
END &&

SELECT EXP,Employee_ROLE(EXP)FROM data_science_team ;
DELIMITER $$

CREATE INDEX idx_first_name ON EMP_RECORD(FIRST_NAME(20)); 
SELECT * FROM EMP_RECORD WHERE FIRST_NAME='Eric';
DELIMITER $$

update EMP_RECORD set salary=(select salary +(select salary*.05*EMP_RATING));
SELECT *FROM EMP_RECORD;
DELIMITER $$

SELECT EMP_ID,FIRST_NAME,LAST_NAME,SALARY,COUNTRY,CONTINENT,AVG(salary)OVER(PARTITION BY COUNTRY)AVG_salary_IN_COUNTRY,
AVG(salary)OVER(PARTITION BY CONTINENT)AVG_salary_IN_CONTINENT, COUNT(*)OVER(PARTITION BY COUNTRY)COUNT_IN_COUNTRY,
COUNT(*)OVER(PARTITION BY CONTINENT)COUNT_IN_CONTINENT FROM emp_record;



